name: Build & Release APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      # Ensure gradlew is executable
      - name: Fix gradlew permissions
        run: chmod +x ./gradlew

      # Clean and build release APK
      - name: Build APK
        run: ./gradlew clean assembleRelease --no-daemon --stacktrace

      - name: Upload APK to Workflow Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: app/build/outputs/apk/release/app-release.apk

  release:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download APK from Build
        uses: actions/download-artifact@v4
        with:
          name: app-release-apk

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: app-release.apk
          tag_name: v${{ github.run_number }}
          name: "Release v${{ github.run_number }}"
          body: |
            Automated release for build #${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
